services:
  nginx:
    build: ./requirements/nginx
    image: nginx_img
    container_name: nginx_container
    restart: always
#    ports:
#      - MUST be only accesible via 443 -> "443:443"

#  mariadb:
#    build: ./requirements/mariadb
#    restart: always

#  wordpress:
#    build: ./requirements/wordpress
#    restart: always