services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    pull_policy: never
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - ./.env
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    pull_policy: never
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    pull_policy: never
    restart: always
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - ./.env
    networks:
      - inception

volumes:
  wordpress_files:
    driver: local                                 # Use local driver to manage files (docker standard)
    driver_opts:
      type: none                                  # Don't use any special file system
      device: /home/antonimo/data/wordpress_files # Path must exist
      o: bind                                     # Use "bind mount", link host and container
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/antonimo/data/mariadb_data
      o: bind

networks:
  inception:
    driver: bridge

# BEFORE: WORK WITHOUT LOCAL VOLUMES
# volumes:
#   wordpress_files:
#   mariadb_data:

# networks:
#   inception:
#     driver: bridge