services:
  nginx:
    build: ./requirements/nginx
    image: nginx_img
    container_name: nginx_container
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html # Just need save wordpress files in this directory
    depends_on:
      - wordpress
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    image: mariadb_img
    container_name: mariadb_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASS=${SQL_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress_img
    container_name: wordpress_container
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${SQL_USER}
      - WORDPRESS_DB_PASSWORD=${SQL_PASS}
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress_files:
  mariadb_data: