services:
  nginx:
    build: ./requirements/nginx
    image: nginx_img
    container_name: nginx_container
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html # Just need save wordpress files in this directory
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    image: mariadb_img
    container_name: mariadb_container
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress_img
    container_name: wordpress_container
    restart: always
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb

volumes:
  wordpress_files: